#!/usr/bin/env bash
# h100/setup.sh — one-shot bootstrap for an H100 box.
# Run once, idempotent. Brings the box from clean Ubuntu/Debian to "ready to autoresearch".
#
# Assumes: SSH key is in your agent, ANTHROPIC_API_KEY env var is set or will be entered.
# Run with:
#   curl -L https://raw.githubusercontent.com/cmbenello/gpu-research/research/overnight-runs-cs-uchicago/h100/setup.sh | bash
# Or after cloning:
#   bash h100/setup.sh
#
set -euo pipefail

# ── 0. Configuration ─────────────────────────────────────────────────────────
REPO_URL="git@github.com:cmbenello/gpu-research.git"
BRANCH="research/overnight-runs-cs-uchicago"
WORK_DIR="${WORK_DIR:-$HOME/gpu-research}"
DATA_DIR="${DATA_DIR:-$HOME/data}"
RESULTS_DIR="${RESULTS_DIR:-$WORK_DIR/results/h100_runs}"

log() { echo "[$(date '+%H:%M:%S')] $*"; }
fail() { echo "[FATAL] $*" >&2; exit 1; }

# ── 1. Detect environment ────────────────────────────────────────────────────
log "Detecting environment..."
nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader \
    || fail "nvidia-smi failed — driver not installed?"

CUDA_VER=$(ls /usr/local/ 2>/dev/null | grep -oP 'cuda-12\.[0-9]+' | sort -V | tail -1)
[ -z "$CUDA_VER" ] && fail "No CUDA 12.x found in /usr/local. Install CUDA 12.4+ first."
export CUDA_HOME="/usr/local/$CUDA_VER"
log "Using $CUDA_HOME"

# Hopper compute capability
# (multi-GPU box: `nvidia-smi | head -1` closes the pipe early → SIGPIPE on
# nvidia-smi → set -o pipefail kills the script. Disable pipefail locally.)
set +o pipefail
GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
case "$GPU_NAME" in
    *H100*|*H800*) ARCH="sm_90" ;;
    *A100*)        ARCH="sm_80" ;;
    *RTX*4090*|*L40*) ARCH="sm_89" ;;
    *RTX*30*)      ARCH="sm_86" ;;
    *RTX*20*|*RTX*6000*|*Quadro*RTX*) ARCH="sm_75" ;;
    *P100*|*P5000*|*Pascal*) ARCH="sm_60" ;;
    *) ARCH=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | head -1 | tr -d '.' | sed 's/^/sm_/') ;;
esac
set -o pipefail
log "GPU: $GPU_NAME → $ARCH"

# ── 2. System packages ───────────────────────────────────────────────────────
log "Installing system packages..."
if command -v apt-get >/dev/null; then
    sudo apt-get update -qq
    sudo apt-get install -y -qq build-essential git tmux htop python3-pip python3-venv \
        curl wget jq parallel pigz numactl 2>&1 | tail -3
fi

# ── 3. Python deps ───────────────────────────────────────────────────────────
log "Installing Python deps..."
pip3 install --user --quiet --upgrade pip 2>&1 | tail -1 || true
pip3 install --user --quiet duckdb polars pyarrow numpy matplotlib pandas tabulate 2>&1 | tail -3

# ── 4. Node.js + Claude Code ─────────────────────────────────────────────────
if ! command -v claude >/dev/null; then
    log "Installing Node.js + Claude Code..."
    if ! command -v node >/dev/null; then
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash >/dev/null 2>&1
        export NVM_DIR="$HOME/.nvm"
        # shellcheck disable=SC1091
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        nvm install --lts >/dev/null 2>&1
    fi
    npm install -g @anthropic-ai/claude-code 2>&1 | tail -3
fi
log "Claude version: $(claude --version 2>&1 || echo 'NOT INSTALLED')"

# ── 4b. tpchgen-cli (10-17x faster TPC-H gen than DuckDB dbgen) ───────────────
if ! command -v tpchgen-cli >/dev/null; then
    log "Installing tpchgen-cli (Rust)..."
    if ! command -v cargo >/dev/null; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable >/dev/null 2>&1 \
            || log "  rustup install failed (non-fatal — duckdb fallback will be used)"
        # shellcheck disable=SC1091
        [ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
    fi
    if command -v cargo >/dev/null; then
        cargo install tpchgen-cli 2>&1 | tail -3
    fi
fi
log "tpchgen-cli: $(tpchgen-cli --version 2>&1 | head -1 || echo 'NOT INSTALLED — duckdb fallback will be used')"

# ── 5. Clone or update repo ──────────────────────────────────────────────────
if [ ! -d "$WORK_DIR/.git" ]; then
    log "Cloning $REPO_URL → $WORK_DIR"
    git clone "$REPO_URL" "$WORK_DIR"
fi
cd "$WORK_DIR"
git fetch origin
git checkout "$BRANCH"
git pull --ff-only

# ── 6. Build everything ──────────────────────────────────────────────────────
log "Building gpu_crocsort (arch=$ARCH)..."
cd "$WORK_DIR/gpu_crocsort"
export PATH="$CUDA_HOME/bin:$PATH"
export LD_LIBRARY_PATH="$CUDA_HOME/lib64:${LD_LIBRARY_PATH:-}"

make ARCH="$ARCH" 2>&1 | tail -3
make ARCH="$ARCH" external-sort-tpch-compact 2>&1 | tail -3
make ARCH="$ARCH" external-sort-tpch 2>&1 | tail -3
make ARCH="$ARCH" external-sort 2>&1 | tail -3

# ── 7. Set up dirs + env ─────────────────────────────────────────────────────
mkdir -p "$DATA_DIR" "$RESULTS_DIR"
df -h "$DATA_DIR" | tail -1

# Write env file the autoresearch loop will source
cat > "$WORK_DIR/h100/env.sh" <<EOF
# Generated by h100/setup.sh — auto-sourced by autoresearch
export CUDA_HOME=$CUDA_HOME
export PATH=\$CUDA_HOME/bin:\$PATH
export LD_LIBRARY_PATH=\$CUDA_HOME/lib64:\${LD_LIBRARY_PATH:-}
export GPU_ARCH=$ARCH
export WORK_DIR=$WORK_DIR
export DATA_DIR=$DATA_DIR
export RESULTS_DIR=$RESULTS_DIR
export REPO_BRANCH=$BRANCH
EOF

# Pin GPU clocks to deterministic state for benchmarking
sudo nvidia-smi -pm 1 >/dev/null 2>&1 || log "  (couldn't enable persistence mode — non-fatal)"

# ── 8. Smoke test ────────────────────────────────────────────────────────────
log "Smoke test: 1M synthetic int32 sort..."
./gpu_crocsort --num-records 1000000 --verify 2>&1 | tail -8

# ── 9. Generate small TPC-H seed (SF10) ──────────────────────────────────────
if [ ! -f "$DATA_DIR/lineitem_sf10.bin" ]; then
    log "Generating TPC-H SF10 (~7 GB) for verification (using fast generator)..."
    cd "$DATA_DIR"
    python3 "$WORK_DIR/h100/gen_tpch_fast.py" 10 lineitem_sf10.bin 2>&1 | tail -3
fi

# ── 10. End-to-end verify ────────────────────────────────────────────────────
log "End-to-end SF10 sort verify..."
cd "$WORK_DIR/gpu_crocsort"
# Pass --runs 1 explicitly so the compact binary RUNS its verifier — without
# it, fast-path silent FAILs (see h100/results/0.1) get hidden behind a clean
# exit code. 0.1.1 follow-up.
./external_sort_tpch_compact --input "$DATA_DIR/lineitem_sf10.bin" --runs 1 2>&1 \
    | grep -E "PASS|FAIL|VIOLATION at|GB/s|^CSV" | head -8 \
    | tee /tmp/setup_verify_sf10.log
if grep -qE "FAIL|VIOLATION at" /tmp/setup_verify_sf10.log; then
    fail "SF10 compact verify failed — see /tmp/setup_verify_sf10.log"
fi

log ""
log "════════════════════════════════════════════════════════════════"
log "  H100 BOOTSTRAP COMPLETE"
log "════════════════════════════════════════════════════════════════"
log ""
log "Next step:  bash $WORK_DIR/h100/start_autoresearch.sh"
log "Stop with:  bash $WORK_DIR/h100/stop_autoresearch.sh"
log ""
log "All env in: $WORK_DIR/h100/env.sh"
log "Results in: $RESULTS_DIR"
log ""

date > "$WORK_DIR/h100/.bootstrap_done"
